name: Singularity build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        singularity_version: ['3.7.3']

    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    steps:
      - name: Check out code for the container build
        uses: actions/checkout@v4

      - name: Install useful utilities
        run: |
          set -e
          if command -v apk >/dev/null 2>&1; then
            apk update
            apk add --no-cache tree figlet wget bash coreutils
          elif command -v apt-get >/dev/null 2>&1; then
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y tree figlet wget
          elif command -v yum >/dev/null 2>&1; then
            yum install -y tree figlet wget
          else
            echo "No known package manager found; skipping utility install."
          fi

      - name: Free disk space
        run: |
          set -e
          [ -d /opt/ghc ] && rm -rf /opt/ghc
          [ -d /usr/local/lib/android ] && rm -rf /usr/local/lib/android
          [ -d /usr/share/dotnet ] && rm -rf /usr/share/dotnet
          if command -v docker >/dev/null 2>&1; then
            docker image prune -af
          fi

      - name: Build and test containers
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          for dir in */ ; do
            # Skip non-directories (guarded by nullglob) and the images/ dir
            [[ "$dir" == "images/" ]] && continue

            echo "==> Entering $dir"
            cd "$dir"

            if [[ ! -f .ignore ]]; then
              echo "Building container in $dir"
              bash ./build.sh

              if [[ -f ./test.sh ]]; then
                echo "Running tests in $dir"
                bash ./test.sh
              else
                echo "Test file n
